version: "3"
services:

  auth_db:
    image: postgres:12-alpine
    container_name: auth_db
    restart: always
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  product_db:
    image: postgres:12-alpine
    container_name: product_db
    restart: always
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  sales_db:
    image: mongo:6.0
    container_name: sales_db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sales
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27018:27017
      - 28017:28017

  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sales
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

